services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: develop
    # Docker-in-Docker を有効にするために privileged モードを使用
    privileged: true
    env_file:
      # Claude Code を Bedrock 経由で使うときに設定してください。
      - ../.aws.env
      # その他諸々の環境変数
      - ../.env
    volumes:
      - type: bind
        source: ..
        target: /app
      # AWSのmcpサーバー接続のために接続情報を渡すための設定。
      # あらかじめ ../private 配下に coinfg と credentials を配置してください
      - type: bind
        source: ../private/.aws
        target: /root/.aws/
      # devcontainer を使っているとgitの設定を求められることがあるので渡しておく
      - ~/.gitconfig:/root/.gitconfig:ro
    tty: true
    stdin_open: true
    environment:
      - PYTHONPATH=/app
